version: "3.3"

services:
  database:
    image: postgres
    container_name: database_eganet
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=master
      - POSTGRES_DB=eganet
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
